Create a Cronjob script and plugin event
mantisbt/mantisbt pull request #1731
Opened 2021-01-17 09:54 UTC by vboctor

This way there is one cronjob script to execute which triggers an event, then all plugins can hook into it.

Fixes #27882

2021-01-17 23:10 UTC, dregad requested changes

2021-01-17 23:10 UTC, dregad commented on scripts/cronjob.php
> + */
_Cron script to trigger cronjob_ is somewhat redundant, suggest replacing by
```
Cron script to allow scheduled execution of plugin tasks.
```

Add 
```
 *
 * @package scripts
 * @copyright Copyright 2021  MantisBT Team - mantisbt-dev@lists.sourceforge.net
 * @link https://mantisbt.org
```

2021-01-17 23:10 UTC, dregad commented on scripts/cronjob.php
> +	echo "cronjob.php is not allowed to run through the webserver.\n";
```
echo basename( __FILE__ ) . " is not [...]
```

2021-01-24 07:54 UTC, vboctor commented
@dregad comments addressed.

2021-02-06 11:35 UTC, dregad approved these changes

2021-02-14 00:45 UTC, merged