String optimizations for English language
mantisbt/mantisbt pull request #1765
Opened 2021-07-11 10:40 UTC by atrol

Fixes [#28905](https://mantisbt.org/bugs/view.php?id=28905)

2021-07-14 17:06 UTC, dregad requested changes
While I'm fine with removing the "Manage" prefix from the tabs and most of the links as it is redundant

![image](https://user-images.githubusercontent.com/449891/125663119-5ba82ac6-1a78-42c2-a7e3-c4a7b057a929.png)

bear in mind that these strings are also used as page title so the browser tab would now e.g. display `Users` instead of `Manage Users` which IMO was better.

![image](https://user-images.githubusercontent.com/449891/125663364-8f46ec7f-bc9b-4ac3-8321-0694173185ee.png)

2021-07-14 20:14 UTC, atrol commented on lang/strings_english.txt
> +$s_schema_version = 'Database Schema Version';
Obvious for you and me, but not for MantisBT newbies.
Furthermore we use `Database Schema` at various other places.

2021-07-14 20:53 UTC, atrol commented
> While I'm fine with removing the "Manage" prefix from the tabs and most of the links as it is redundant
> bear in mind that these strings are also used as page title so the browser tab would now e.g. display `Users` instead of `Manage Users` which IMO was better.

@dregad right, the title was better.
I am not sure if introducing separate strings for link and title and rewriting some functions is a good idea.
As I don't have time to implement something like that at the moment, there are two options.
- nice labels on the tabs
- nice page titles

Let me know what you prefer

2021-07-14 21:34 UTC, dregad commented on lang/strings_english.txt
> +$s_schema_version = 'Database Schema Version';
OK

2021-07-14 21:48 UTC, dregad commented
> I am not sure if introducing separate strings for link and title and rewriting some functions is a good idea.

I agree, it's not worth the effort for sure, and probably not such a good idea.

> Let me know what you prefer

A bit of a tough call... 
- Personally, I like having descriptive page titles, so the current display which makes it very clear what the tab is about suits me fine. 
- On the other hand, it is also somewhat obvious/implied if I read e.g. *User - MantisBT* or *Plugins - MantisBT* that I'm on the management page, as there are no other places.

So maybe I just need to get used to the change... Let me think about it some more and I'll get back to you (and do remind me if I don't me respond in the next couple weeks :wink: )

2021-07-18 22:58 UTC, vboctor commented
I'm in favor of this change.

2021-07-24 15:55 UTC, atrol commented
@dregad last chance to object, will merge tomorrow.

2021-07-24 19:37 UTC, dregad commented
>
> @dregad <https://github.com/dregad> last chance to object, will merge
> tomorrow.
>
Sorry, I said in a couple weeks (meaning 2) as I'm currently on vacation
with other things to think about than Mantis 😉

I'll look at it when I'm back home (Monday).

>

2021-07-24 20:18 UTC, atrol commented
No rush, enjoy your vacation.

2021-07-27 16:17 UTC, dregad approved these changes

2021-07-27 19:47 UTC, merged