Attachment to new tab
mantisbt/mantisbt pull request #1767
Opened 2021-08-04 14:12 UTC by MaloMn

I think the behavior when viewing attachment should change: when clicking on an image in a bugnote, it displays it in the same tab. I think it would be better to redirect this full display of the image to a new tab. That would allow you to go back and forth between seeing the image and seeing the bugnote text associated.

This new redirection would be effective for both clicking on the icon or on the name of the attachment (as shown below), and also when clicking on an image preview in a bugnote, or a preview of an audio / video.

![image](https://user-images.githubusercontent.com/9255251/128195047-1609dc70-61b5-4908-b763-3a5d41473cfd.png)

2021-08-04 18:01 UTC, atrol commented
Worth to read in this context https://mantisbt.org/forums/viewtopic.php?f=2&t=25561

2021-08-06 08:31 UTC, MaloMn commented
Thanks for the forum link.

From what I understand:
* It's something that should be an option, and not something permanent,
* It's unclear whether it should behave the same for pdf / audio / images / text files.

I don't think setting an option for each file type is a good idea (I agree with your argument that it would confuse users), and I also think that having an option for all file types is a good thing. I don't think it woud be right to open pdf files in a new tab, and not images. In both cases, you have to use the browser "Go back" button if it does not open in a new tab.
I also don't think that the question about whether the browser can handle displaying the attachment is valid, because whether it is in a new tab or not, the browser will behave the same. The only major change in my view is if it can't display the attachment : it will open a new tab and close it immediately, before opening the dialog box to open the attachent in another software.

I'll reply in this forum with a link to this Pull Request.

Following up from what I've said, I added a constant in config_default_inc.php, and a function in print_api.php that returns the `target` tag, filleed with either *_self* or *_blank*. I'm not sure whether it's the right way to do it, but it works on my local Mantis installation.

2021-10-30 17:10 UTC, dregad requested changes

2021-10-30 17:10 UTC, dregad commented on core/print_api.php
> + * Returns target tag to be added in attachment links
*target* is not a tag, it's an attribute

2021-10-30 17:10 UTC, dregad commented on core/print_api.php
> +function get_attachment_link_target() {
By convention, we usually prefix functions with the API's name, so this should be called *print_attachment_link_target()*

2021-10-30 17:10 UTC, dregad commented on config_defaults_inc.php
> +
I believe it would make more sense to move this to the *Bug Attachments Settings* section

2022-01-26 09:08 UTC, dregad commented
@MaloMn as you have not responded to the review, I'm going to close this PR without merge. Feel free to reopen after making the required changes.

2022-01-26 09:08 UTC, closed without merging

2024-09-07 15:46 UTC, dregad commented
Replaced by #1994