implementations in the rest api
mantisbt/mantisbt pull request #1817
Opened 2022-05-26 00:29 UTC by gilsonjoanelo

I created some implementations in the rest api, I am using it in a personal project and I missed some functions that have in the SOAP api and I implemented some in the new api, among them the possibility of searching a question through its summary. Another improved point was the ability to remove or add a version of a given project.

2022-05-26 15:51 UTC, gilsonjoanelo commented
thinking in this way, it is not a good idea, because more than one record can come, it only returns a single record if it is exactly the same. But the steps of changing and removing project versions can exist right? I did the search for the summary due to an integration that we have in our project, but thinking about your vision, I realized that it is not the best practice to adopt, I will review the code.

2022-05-28 15:36 UTC, atrol commented
>  But the steps of changing and removing project versions can exist right?

I think so, but would like to get some feedback from @vboctor

I created [Issue 30415](https://www.mantisbt.org/bugs/view.php?id=30415) to track this change.
The issue must be referenced in the commit message via `Fixes #30415`

2022-05-28 16:07 UTC, dregad requested changes
I second what @atrol said about searching for Issues by Summary; mc_issue_get_id_from_summary() is is flawed, because if there is more than 1 match for the given summary, it will just return the first one found. Therefore I also don't think this should be implemented in REST API as-is, and changes to *issues_rest.php* should be removed from this PR.

Some code review comments follow regarding the Version update/delete endpoints.

NB: I did not actually test the code yet.

2022-05-28 16:07 UTC, dregad commented on core/commands/VersionUpdateCommand.php
> +        $t_obsolete = $this->payload( 'obsolete', false );
Providing a default value will potentially result in unexpectedly changing the target field if it is not provided by the client in the payload.

In my opinion, in an Update operation the command should only update the information provided in the payload, and leave other fields unchanged. @vboctor what do you think ?

2022-05-28 16:07 UTC, dregad commented on core/commands/VersionUpdateCommand.php
> +        $t_version = version_get($t_id);
Coding guidelines

2022-05-28 16:07 UTC, dregad commented on core/commands/VersionRemoveCommand.php
> +		$t_version_id = version_remove($t_id, null);
Coding guidelines

2022-05-28 16:07 UTC, dregad commented on core/commands/VersionUpdateCommand.php
> +        $t_version_id = version_update($t_version);
Coding guidelines

2022-06-15 16:34 UTC, dregad commented
@gilsonjoanelo are you planning to address the review comments ? If not, I'll close the PR.

2022-06-15 16:39 UTC, closed without merging

2023-04-23 01:00 UTC, vboctor commented
See related PR #1883