Refactor access level check for note links
mantisbt/mantisbt pull request #2000
Opened 2024-05-05 19:56 UTC by vboctor

Fixes #[34434](https://mantisbt.org/bugs/view.php?id=34434)

2024-05-05 22:09 UTC, dregad requested changes
This is technically not a refactoring since you are changing the code's behavior. Please change the commit message to reflect what is being done.

2024-05-05 22:09 UTC, dregad commented on core/string_api.php
> +									|| bugnote_get_field( $c_bugnote_id, 'reporter_id' ) == auth_get_current_user_id()
Use the $t_user_id variable defined above

2024-05-06 06:52 UTC, vboctor commented
@dregad done.

2024-05-12 15:38 UTC, dregad approved these changes

2024-05-12 15:38 UTC, merged