Optimize lang_load() function by replacing preg_replace()
mantisbt/mantisbt pull request #2059
Opened 2024-12-21 06:26 UTC by raspopov

with str_starts_with(), and substr().

For 'auto' language and non-English browsers it was about 2500 preg_replace() calls per page load, making this function in the top 10 of CPU eaters according to xDebug2 profiler. No more.

2024-12-21 06:32 UTC, raspopov commented
Ah, str_starts_with() requires PHP 8...

2024-12-21 17:23 UTC, dregad requested changes
> Ah, str_starts_with() requires PHP 8...

FYI we'll increase the minimum PHP version from 7.4 to 8.1 when Ubuntu 20.04 LTS reaches end of standard support (April 2025).

If we're going after performance, then we strpos() is slightly faster than strncmp() - although probably not by a factor likely to make a noticeable difference with only a few thousand iterations.

Please open an issue in the tracker.

2024-12-21 19:02 UTC, raspopov commented
Opened.

2024-12-22 10:44 UTC, dregad approved these changes

2024-12-22 10:50 UTC, dregad commented
Merged in 9e2b936c7d5bfbad273c757caaa965b6ea183620, thanks for your contribution

2024-12-22 10:50 UTC, closed without merging